[package]
name = "oosc-core"
version = "0.1.0"
edition = "2021"
authors     = [ "karasikq <romastepanuik@gmail.com>" ]
description = "TUI synthesizer"

[dependencies]
cgmath = "0.18.0"
assert_approx_eq = "1.1.0"
rayon = "1.8.0"
cpal = "0.15.2"
midly = "0.5.3"
hound = "3.5.1"
